[tool.black]
line-length = 120
target-version = ['py311']

[tool.isort]
profile = "black"
line_length = 120

[tool.mypy]
python_version = '3.11'

disallow_untyped_decorators = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
warn_unused_ignores = true

allow_untyped_globals = true
warn_no_return = false
disallow_untyped_calls = false
allow_redefinition = true

[[tool.mypy.overrides]]
module = 'stable_baselines3'
ignore_missing_imports = true